### ISSUE TITLE
【新機能】slack bot apiで動くようにする

### ISSUE THREAD

**Issue by chory-amam** [chory-amam/slack-capybara#92]
XMPPを使ったslackとの連携方法では、新規ユーザーを登録する必要がでてしまうので、integrationのbotで動けるようにslack bot apiに対応する。

slack bot apiにすることで以下のことができなくなるがbotをintegrationで扱うことが可能になる
・direct messageで反応させることができない(プライベートグループであれば可能)
・@bot名でコマンド実行できない(bot名 コマンド　でコマンド実行はできる)

設定はcapybara.yamlに記述するようにし、従来のxmppとslack bot apiのどちらのモードも選べるようにしたい。

**Comment by masahitojp** [comment]
#93 の実装で、slack bot api でも以下の点が実現できました

> slack bot apiにすることで以下のことができなくなるがbotをintegrationで扱うことが可能になる
> ・direct messageで反応させることができない(プライベートグループであれば可能)
> ・@bot名でコマンド実行できない(bot名 コマンド　でコマンド実行はできる)

**Comment by chory-amam** [comment]
[![LGTM](http://lgtm.in/p/k6arrXXMn)](http://lgtm.in/i/k6arrXXMn)

[:+1:](http://lgtm.in/u/k6arrXXMn)
